### ISSUE TITLE
请问遇到兼容性问题应该怎么解决

### ISSUE THREAD

**Issue by BlueRose-32** [AaronFeng753/Waifu2x-Extension#1]
我是昨晚帖子里遇到使用问题的人
之前3.1版本使用waifu2x-ncnn-vulkan这个模式处理视频时，进度会一直卡在0不动，创建的新文件也不会进行处理，右侧的计时功能则正常
将模式换做waifu2x-converter时虽然会正常运作，但每当程序将视频处理完毕后会出现报错现象，报错的同时原本由程序创建处理好的新文件也全被程序自动删除了

以上问题在换了3.15版本后，于作者您新增加的兼容性检测功能得到了解答：
Compatible with waifu2x-ncnn-vulkan :  False
Compatible with waifu2x-converter :  True
Compatible with Anime4k :  False
请问以上三条兼容性问题应该如何解决？
![20190915174404](https://user-images.githubusercontent.com/55369325/64932076-1a8e1780-d86f-11e9-8260-21d4052e8ca6.png)

**Comment by AaronFeng753** [comment]
截图里的 红色字 的问题是 你输入的视频路径中含有中文 造成了兼容性问题,我暂时没有找到解决这个兼容性问题的办法. 只能更改文件名和文件夹名称,去掉里面的中文.
如果想尝试修复兼容Anime4k的问题, 可以安装最新的jre和jdk, 然后再检查一下看看是否兼容.
如果想尝试修复兼容waifu2x-ncnn-vulkan的问题, 可以安装最新显卡驱动, 然后再检查一下看看是否兼容, 如果依旧不兼容, 那就表示你的显卡支持的vulkan版本过于老旧. 或者压根不支持vulkan

**Comment by AaronFeng753** [comment]
我的建议是先安装最新的显卡驱动, 测试ncnn-vulkan是否可以兼容, 如果可以兼容则换到ncnn-vulkan,那个速度更快画质更好. 不兼容就继续用converter, 那个兼容性好, 效果也不错, 就是速度慢点.
Anime4k我本来就不推荐用, 所以你也别折腾了, 恕我直言anime4k真的挺垃圾, 唯一优点就是快, 对画质几乎没有提升, 要不是有几个NC总在我酷安评论区底下提这个垃圾, 我才不会集成. 我纯粹就图个清静才集成这个垃圾.
(如果是amd显卡, 则安装最新的测试版本驱动, 稳定版的vulkan可能不够新, 我的显卡就是这样, 英伟达和intel我不是很了解)

**Comment by BlueRose-32** [comment]
多谢解答
之前我有担心过中文路径问题，所以输入的视频路径是没有中文的，但是使用converter模式处理视频时，依旧会出现那张图里的报错现象，同样的模式下处理图片可以正常运作，但偏偏视频就不行，不知道是我的电脑系统有问题，还是我少安装了什么。
我的系统是win7 64位 显卡是gtx 1070 按照您说的安装最新显卡驱动后还是和之前一样，检测时ncnn-vulkan显示不兼容，处理视频时进度不会动，去软件运作时添加的文件夹里查看也发现没有对那些新文件进行处理，看来我真的该去换系统了。

**Comment by AaronFeng753** [comment]
> 多谢解答
> 之前我有担心过中文路径问题，所以输入的视频路径是没有中文的，但是使用converter模式处理视频时，依旧会出现那张图里的报错现象，同样的模式下处理图片可以正常运作，但偏偏视频就不行，不知道是我的电脑系统有问题，还是我少安装了什么。
> 我的系统是win7 64位 显卡是gtx 1070 按照您说的安装最新显卡驱动后还是和之前一样，检测时ncnn-vulkan显示不兼容，处理视频时进度不会动，去软件运作时添加的文件夹里查看也发现没有对那些新文件进行处理，看来我真的该去换系统了。

酷安上的网友在他的1070上测试过, 可以运行没有问题. 
关于视频路径, 我仔细看了一下, 好像是我代码的问题, 你可以试试把视频放到一个文件夹里, 例如 F:\video\

**Comment by AaronFeng753** [comment]
问题已经修复了, 等待下一版本更新吧
