### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by DraGoran4** [AaronFeng753/Waifu2x-Extension#11]
I got this error message at some point, i thoiught it only occurs at broken Gif files, but thats not the case,

I also recommend the possibility to save files in a different folder thasn the input folder and make tighter scale values possible like caffee does 1, 5/ 3 etc .

System Specs:

Win 10 Home
Waifu Extension 4.1
Amd Radeon Saphire R9 290 Oci Tri X

**Comment by DraGoran4** [comment]
https://imgur.com/a/dKvuM6o

**Comment by AaronFeng753** [comment]
pls send me the gif which cause the error

**Comment by DraGoran** [comment]
not one gifs many and this is one of them

**Comment by DraGoran** [comment]
k

**Comment by DraGoran4** [comment]
https://imgur.com/8xz8458

**Comment by DraGoran4** [comment]
one of many

**Comment by DraGoran4** [comment]
i also have the problem that at some point my pc crashes, i did a stress test  for gpu and for cpu and my graphic card reached  on 40 k resolution just 75 degrees, on using waifu 2x extension it doesnt even reach 60 degrees  the temperature is around 54, I have tested the program witth files from different hdds and the problem  remains. I have this problem only using Waifu2xExtension, till now i found no solution. My Graphic Card and CPU are stable, no crash or anything, the time were my pc crashes is totally random, sometimes it happens right after i started the scaling, sometimes inbetween it or after 20 minutes, the pic were it happens is also random, it does not matter, when crashing the pc just shutsoff no bluescreen or anything and restarts again normally without booting into Extended mod, as if i just did a normal restart. My drivers are recent and updated. 

This issue is not related to my first problem, the pc dodesnt crash on that.

**Comment by AaronFeng753** [comment]
This project will not be updated anymore, I am developing a QT-based GUI version
