### ISSUE TITLE
Notification sound option not saving after closing

### ISSUE THREAD

**Issue by flavw** [AaronFeng753/Waifu2x-Extension#14]
I'm testing the new version with GUI and I really like that notification sound. However, when checking the option and closing the program, it is deselected the next time the program is used.

**Comment by AaronFeng753** [comment]
This is normal, I haven't add the function of save setting options.
The GUI version's development  is still at early stage. 
And, for any suggestions and bug reports about the gui version, please submit an issue in the gui project, do not submit any issue under this project.

**Comment by flavw** [comment]
Understand. Sorry I'm new to the site.
