### ISSUE TITLE
GUI is too wide

### ISSUE THREAD

**Issue by flavw** [AaronFeng753/Waifu2x-Extension#15]
As the program is usually used by dragging images inside, the interface is partially hidden on a 1920x1080 screen (picture below), including the Start button. I believe it would be interesting to make the interface less wide, for example by joining GIF and Videos in one tab or reducing the width between the tabs.

![image](https://user-images.githubusercontent.com/60268722/73089904-fcd45d00-3eb5-11ea-8478-81dfb2075107.png)

**Comment by AaronFeng753** [comment]
Thanks, i will consider your suggestion.
