### ISSUE TITLE
Output converted files to different path?

### ISSUE THREAD

**Issue by AkatsukiiDesu** [AaronFeng753/Waifu2x-Extension#4]
Hello :)

I was wondering if there was a way to do the following:

1. Set Scaled_Waifu2x to NOT be removed upon converting files (as when I convert new images in the folder, the files that are already in Scaled_Waifu2x are deleted)
2. Set an ouput path for the converted files to move to after conversion

At the moment I currently have my settings to delete the original after conversion. If i then add a new picture to the folder, run the conversion again, all images that were in scaled_waifu2x are deleted, leaving ONLY the recently added image.

I can at the moment just setup a script to move anything in "scaled_waifu2x" to a different folder.

Thanks :)

**Comment by AaronFeng753** [comment]
OK, I will consider your suggestions, thank you.

**Comment by AaronFeng753** [comment]
This project will not be updated anymore, I am developing a QT-based GUI version
