### ISSUE TITLE
能否设置图片质量？

### ISSUE THREAD

**Issue by mikulolicon** [AaronFeng753/Waifu2x-Extension#7]
试用了最新版本测试图片，出图大小，质量都和http://waifu2x.udp.jp/出图有较大差距。（原图700kb左右，http://waifu2x.udp.jp/ 【照片模式，2倍放大，降噪中】出图5MB，修复效果满意，Waifu2x-Extension 默认参数【2倍放大，降噪2】出图940kb竟然出现了许多原图未出现的锯齿）image quality 参数修改没有效果，没看到有其他修改出图质量的选项，想问下能否解决这个问题？毕竟这个gui界面还是很不错的，显卡是RX570

**Comment by AaronFeng753** [comment]
自己看user guide
