### ISSUE TITLE
视频放大倍数希望增加1.5倍选项

### ISSUE THREAD

**Issue by mikulolicon** [AaronFeng753/Waifu2x-Extension#8]
很多人现在依然是使用1080P的屏幕，720P的视频可能是会需要waifu2x拉升的主要视频源，使用3.8版本测试视频压制过程中，发现和图片一样只有整数倍率（1/2/4/8）放大，只是图片而言其实还好，但是就视频来说，720P 2X放大直接就来到2K分辨率了，即便waifu2x足够优秀，拉伸倍数越高一定会造成细节损失越大，希望能增加1.5倍率放大选项或者直接能够像caffe版本一样可以.1倍率手动设置，这样无论是图片还是视频都可以灵活很多

**Comment by whisperice** [comment]
主要是所有的依赖包都是x2起步的，目前还没有看到.1倍率，估计是不好搞的。

**Comment by whisperice** [comment]
估计caffe的.1是不是先x2之后再往下缩小的。。
